name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: actions/cache@v3
        with:
          path: |
            ~/go
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: 1.7.0
          args: build --rm-dist --snapshot
