name: release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'dev-')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - uses: actions/cache@v3
        with:
          path: |
            ~/go
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: Compute tag name
        id: tag-name
        run: echo "::set-output name=tag-name::${GITHUB_REF#refs/tags/}"
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: 1.7.0
          args: release --parallelism 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.tag-name.outputs.tag-name }}
