name: release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'dev-')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Compute tag name
        id: tag-name
        run: echo "::set-output name=tag-name::${GITHUB_REF#refs/tags/}"
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --parallelism 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.tag-name.outputs.tag-name }}
